name: ClangTidy

on:
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  CheckTidy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: "Install clang tidy"
        uses: ./.github/actions/InstallPackages
        with:
          install-clang-tidy: true

      - name: "Install HLS dialect dependencies"
        uses: ./.github/actions/BuildCirct

      - name: "Install MLIR dialect dependencies"
        uses: ./.github/actions/BuildMlirDialect

      - name: "Configure jlm with HLS and MLIR enabled"
        run: ./configure.sh --enable-mlir=${{ github.workspace }}/lib/mlir-rvsdg --enable-hls=${{ github.workspace }}/build-circt/circt

      - name: "Run clang tidy"
        run: make tidy
